@startuml

class GameLifeTimeScope{}

Player *-- PlayerMover
Player *-- MyInput
Player *-- WeaponController
class Player{
         private PlayerMover _playerMover;
         private MyInput _input;
         IWeapon _weapon;
}
class PlayerMover{
private CharacterController _characterController;
}
class MyInput{}
WeaponController *-- IAttackable
class WeaponController{

}

class HandGun extends IWeapon,IAttackable{}

interface IWeapon{}
interface IAttackable{}

class InGameUIManager{}
class InGameManager{}
@enduml