# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: Install gcovr
        run: |
          sudo pip3 install gcovr
      - name: Install graphviz and doxygen
        run: |
          sudo apt update
          wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
          tar -xzf doxygen-1.10.0.linux.bin.tar.gz
          sudo mv doxygen-1.10.0/bin/doxygen /usr/local/bin/doxygen
          doxygen --version
      - name: Build site
        run: |
          doxygen ./Doxyfile

      - name: push html
        run: |
          git config user.name auto-push
          git config user.email auto-push@example.com
          git add ./html
          git commit -m "auto push from ci" || echo no commits
          git push

